workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Build release AAB
        script: |
          ./gradlew clean bundleRelease
    artifacts:
      - app/build/outputs/bundle/release/*.aab
